spring:
  profiles:
    active: pro
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/*

avatar: /static/images/zhanxianjishu1.jpg
